# Disable line checking on the code blocks and tables.
MD013:
  "code_blocks": false
  "tables": false
  "line_length": 100
# Disable checking for the multiple headings with the same content.
MD024: false
# Allow inline HTML, useful for positioning images.
MD033: false
# link-fragments Link fragments should be valid. Due to the problems with
# vim-markdown-toc plugin and markdown issues with emojis in titles this
# setting needs to be disabled.
MD051: false
