name: "Publish Release"

on:
  workflow_call:
    inputs:
      release_version:
        required: true
        type: string

jobs:
  publish-new-release:
    runs-on: ubuntu-latest

    steps:
      - name: Start
        run: |
          version_cut=$(echo "${{ inputs.release_version }}" | cut -c 2-)
          echo "release_version=${{ inputs.release_version }}" >> $GITHUB_ENV
          echo "release_version_cut=$version_cut" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.release_version }}

      - name: Get latest Changelog entry
        id: changelog-reader
        uses: mindsers/changelog-reader-action@v2.2.3
        with:
          version: ${{ env.release_version_cut }}

      - name: Publish Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: ${{ env.release_version }}
          body: |
            # Release notes

            ${{ steps.changelog-reader.outputs.changes }}
